### ISSUE TITLE
Allow setting entry selection from an input file

### ISSUE THREAD

**Issue by irhs** [ucam-cl-dtg/picky#1]
The client picks up settings from a settings.properties file, which also has a `entrySelection` field, but the client ignores that field. 

It would help me a lot, and probably others too, if we can provide entry selection in the settings.properties file (or other file), and the client enables those entries if they are available for the subset of data, as per the filters.

Right now, every time I change the filter or open the client, I have to go and check each

**Comment by hintzed** [comment]
Thanks for reporting this issue and sorry for the inconvenience. 

I think I managed to fixed this bug. Could you give it a try and let me know if it works?

**Comment by irhs** [comment]
I tested it few times. It works. :thumbsup: Thanks!
